spring.application.name=MyHospitalManagement

spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalDB3
spring.datasource.username=postgres
spring.datasource.password=ram

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql

spring.app.jwtSecretKey=z7B9f2K7Mv4N8X6P1Q3R5W8Z0A2S4D6F9G1H3J5K7L9M0N2B4V6C8X0Z1A3S5D7F
spring.app.jwtExpirationMs=90000

spring.app.refreshTokenExpirationMs=604800000
