package com.example.MyHospitalManagement.dto;

import jakarta.validation.constraints.Future;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Builder;
import lombok.Data;

import java.time.LocalDateTime;

@Data
@Builder
public class AppointmentRequestDto {

    // id must never come from the client — auto-generated by DB
    // private Long id;  ← intentionally removed

    @NotBlank(message = "Reason is required")
    private String reason;

    @NotNull(message = "Appointment time is required")
    @Future(message = "Appointment time must be in the future")
    private LocalDateTime appointmentTime;

    // patientId is NOT accepted from the request body anymore.
    // For PATIENT role  → resolved automatically from the JWT token.
    // For ADMIN role    → passed as a @RequestParam on the endpoint.
    // private Long patientId;  ← intentionally removed

    @NotNull(message = "Doctor ID is required")
    private Long doctorId;
}
